#redis:
#    image: redis
#    ports:
#     - "6379:6379"
main:
  build: ./docker/calls-consumer  
  ports:
     - "30790:30790"
#    links:
#     - redis
  environment:
    EXTERNAL_IP: 192.168.176.220
    REDIS_SERVICE_HOST: 192.168.176.220
    REDIS_SERVICE_PORT: 6379
    RESTCOMM_SERVICE: 192.168.176.220:8080
conference:
  build: ./docker/conference-call
  ports:
   - "30791:30791"
#    links:
#     - redis
  environment:
    EXTERNAL_IP: 192.168.176.220
    REDIS_SERVICE_HOST: 192.168.176.220
    REDIS_SERVICE_PORT: 6379
    RESTCOMM_SERVICE: 192.168.176.220:8080
sms-feedback:
  build: ./docker/sms-feedback
  ports:
   - "30794:30794"  
  environment:
    EXTERNAL_IP: 192.168.176.220
    REDIS_SERVICE_HOST: 192.168.176.220
    REDIS_SERVICE_PORT: 6379
    RESTCOMM_SERVICE: 192.168.176.220:8080
#advertising:
#  build: ./demo-advertising
#  ports:
#   - "7092:7092"
#   - "7093:7093"
#  links:
#   - redis
#  environment:
#    EXTERNAL_IP: 192.168.176.220
#    REDIS_SERVICE_HOST: 192.168.176.220
#    REDIS_SERVICE_PORT: 6379
#    RESTCOMM_SERVICE: 192.168.176.220:7070
#mailagent:
#    build: ./mailagent
#    ports:
#     - "7094:7094"
#    links:
#     - redis
#    environment:
#      EXTERNAL_IP: 192.168.176.220
#      REDIS_SERVICE_HOST: 192.168.176.220
#      REDIS_SERVICE_PORT: 6379
#      RESTCOMM_SERVICE: 192.168.176.220:7070
#      GMAIL_USER: tads2015dataart@gmail.com
#      GMAIL_PASS: gdubina2015
